### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by kzerot** [mashingan/nimffmpeg#4]
Hi! 
Trying to run example with sdl2 on linux, got error 
"could not load: SDL2.dll"
Have sdl2 installed in system, also put SDL2.so in folder with examples. What I'm doing wrong?

**Comment by mashingan** [comment]
That's strange that if you're on Linux it should be `could not load: SDL2.so` . The `.dll` is only on windows. I tried run it on Arch fine last time, but haven't had chance to try it again.  
  
What is your system btw?

Can you run below commands and paste the results here?

* `uname -a`
* `nim -v`

**Comment by kzerot** [comment]
Thanks for really fast reply! 

Problem is in my curvy hands. 
in example 
proc updateYUVTexture*(
    texture: TexturePtr; rect: ptr Rect;
    yPlane: ptr uint8; yPitch: cint;
    uPlane: ptr uint8; uPitch: cint;
    vPlane: ptr uint8; vPitch: cint): cint {.
      cdecl, importc: "SDL_UpdateYUVTexture", dynlib: "SDL2.dll".}

I replaced it to 
      cdecl, importc: "SDL_UpdateYUVTexture", dynlib: "libSDL2.so".}

Works just fine. Maybe need make example crossplatform?

**Comment by mashingan** [comment]
Oof, thanks for pointing it out. Yeah, it was added because the SDL2 Nim version hadn't have that `updateYUVTexture` back then.  
  
I forgot to test it after some one patched it by adding it in code example instead of patching to the Nim SDL2 package.

I'll update it in a bit.

**Comment by kzerot** [comment]
Thanks!
