### ISSUE TITLE
could not load: avcodec(|-55|-56|-57|-58|-59).dll

### ISSUE THREAD

**Issue by kzerot** [mashingan/nimffmpeg#5]
Sorry fo bother you again :)
Now I'm trying to compile for Win10. Forgot how to use it :)
It's compiling ok, but when I run program I have error:
could not load: avcodec(|-55|-56|-57|-58|-59).dll

I also tried to put avcodec-58.dll in folder with executable but error still here.
Same error goes for all examples.

**Comment by mashingan** [comment]
Try to check whether it's available in path or not with command `where avcodec*`. It will tell where the lib resides.  
If it's blank, you can temporarily put the ffmpeg-lib folder path into the `%PATH` with `set PATH=<where ffmpeg lib resides>;%PATH%` with `<where ffmpeg lib>` is just like simple `c:\ffmpeg\bin` or `d:\ffmpeg\bin` or any other places etc.

**Comment by kzerot** [comment]
Have libs in PATH, also have in one folder with executable. Really dunno where can be problem. On linux works just fine.

c:\Git\NimSlides\src>where avcodec*
C:\ffmpeglibs\avcodec-58.dll

c:\Git\NimSlides\src>fplay.exe
could not load: avcodec(|-55|-56|-57|-58|-59).dll

**Comment by kzerot** [comment]
OK, after some magic it's working. Thanks a lot for patience!

**Comment by mashingan** [comment]
Could you elaborate on how you solve it? For reference in case others have same problem.

**Comment by kzerot** [comment]
You need build  ffmpeg with shared libs or just take dlls from zeranoe (for me his site is down now, so I used mirror - https://github.com/advancedfx/ffmpeg.zeranoe.com-builds-mirror), ffmpeg-latest-win64-shared.zip
And then just put ddls in one folder with executable or add path to libs in your PATH. 
Also you need all libs, not only avcodecs.

After all problem was in my hands after all.
